require('dotenv').config();
const { supabaseAdmin } = require('./config/database');

async function checkResponsesTable() {
  try {
    console.log('=== Checking responses table ===');
    
    // Try to select from responses table
    const { data, error } = await supabaseAdmin
      .from('responses')
      .select('*')
      .limit(1);
    
    if (error) {
      console.error('❌ Error accessing responses table:', error);
      
      // Check if table exists by querying information schema
      const { data: tableInfo, error: infoError } = await supabaseAdmin
        .rpc('get_table_info', { table_name: 'responses' });
      
      if (infoError) {
        console.error('❌ Error getting table info:', infoError);
        
        // Try to create the responses table manually
        console.log('\n=== Creating responses table ===');
        const { error: createError } = await supabaseAdmin
          .rpc('exec_sql', {
            sql: `
              CREATE TABLE IF NOT EXISTS responses (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                survey_id BIGINT NOT NULL REFERENCES surveys(id) ON DELETE CASCADE,
                user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                submitted_at TIMESTAMPTZ DEFAULT NOW(),
                is_completed BOOLEAN DEFAULT TRUE NOT NULL,
                completion_time INTEGER,
                created_at TIMESTAMPTZ DEFAULT NOW(),
                updated_at TIMESTAMPTZ DEFAULT NOW(),
                UNIQUE(survey_id, user_id)
              );
              
              -- Indexes
              CREATE INDEX IF NOT EXISTS idx_responses_survey_id ON responses(survey_id);
              CREATE INDEX IF NOT EXISTS idx_responses_user_id ON responses(user_id);
              
              -- RLS
              ALTER TABLE responses ENABLE ROW LEVEL SECURITY;
              
              -- Policies
              CREATE POLICY IF NOT EXISTS "Users can view own responses" ON responses
                FOR SELECT USING (auth.uid()::text = user_id::text);
              
              CREATE POLICY IF NOT EXISTS "Users can create own responses" ON responses
                FOR INSERT WITH CHECK (auth.uid()::text = user_id::text);
              
              CREATE POLICY IF NOT EXISTS "Survey creators can view survey responses" ON responses
                FOR SELECT USING (
                  EXISTS (
                    SELECT 1 FROM surveys 
                    WHERE surveys.id = responses.survey_id 
                    AND surveys.created_by = auth.uid()::text::bigint
                  )
                );
            `
          });
        
        if (createError) {
          console.error('❌ Error creating responses table:', createError);
        } else {
          console.log('✅ Responses table created successfully');
        }
      }
    } else {
      console.log('✅ Responses table exists and is accessible');
      console.log('Sample data:', data);
    }
    
    // Also check answers table
    console.log('\n=== Checking answers table ===');
    const { data: answersData, error: answersError } = await supabaseAdmin
      .from('answers')
      .select('*')
      .limit(1);
    
    if (answersError) {
      console.error('❌ Error accessing answers table:', answersError);
    } else {
      console.log('✅ Answers table exists and is accessible');
    }
    
  } catch (error) {
    console.error('❌ Check error:', error);
  }
}

checkResponsesTable();
