-- Comprehensive Survey Schema for Voxa Application
-- This script provides complete survey functionality including:
-- - Survey creation and management
-- - Question types (multiple choice, text, rating)
-- - Response collection and analysis
-- - Analytics and reporting
-- - Survey permissions and access control

-- Drop existing survey tables to recreate with comprehensive structure
DROP TABLE IF EXISTS answers CASCADE;
DROP TABLE IF EXISTS user_responses CASCADE;
DROP TABLE IF EXISTS questions CASCADE;
DROP TABLE IF EXISTS surveys CASCADE;

-- Main Surveys Table
CREATE TABLE surveys (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  description TEXT,
  created_by BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  status TEXT CHECK (status IN ('DRAFT', 'PUBLISHED', 'CLOSED', 'ARCHIVED')) DEFAULT 'DRAFT' NOT NULL,
  response_count INTEGER DEFAULT 0 NOT NULL,
  target_audience JSONB DEFAULT '[]'::jsonb, -- Array of roles, departments, or specific user IDs
  start_date TIMESTAMP WITH TIME ZONE,
  end_date TIMESTAMP WITH TIME ZONE,
  is_anonymous BOOLEAN DEFAULT FALSE NOT NULL,
  allow_multiple_responses BOOLEAN DEFAULT FALSE NOT NULL,
  require_authentication BOOLEAN DEFAULT TRUE NOT NULL,
  max_responses INTEGER, -- Maximum number of responses allowed
  survey_settings JSONB DEFAULT '{}'::jsonb, -- Additional settings like notifications, etc.
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Questions Table
CREATE TABLE questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  survey_id BIGINT NOT NULL REFERENCES surveys(id) ON DELETE CASCADE,
  text TEXT NOT NULL,
  type TEXT CHECK (type IN ('multiple_choice', 'checkbox', 'short_answer', 'long_answer', 'rating', 'date', 'time', 'email', 'number')) NOT NULL,
  "order" INTEGER NOT NULL,
  is_required BOOLEAN DEFAULT TRUE NOT NULL,
  options JSONB DEFAULT '[]'::jsonb, -- For multiple choice/checkbox questions
  validation_rules JSONB DEFAULT '{}'::jsonb, -- Validation rules for text inputs
  settings JSONB DEFAULT '{}'::jsonb, -- Additional question settings
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- User Responses Table (renamed from responses for clarity)
CREATE TABLE user_responses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  survey_id BIGINT NOT NULL REFERENCES surveys(id) ON DELETE CASCADE,
  user_id BIGINT REFERENCES users(id) ON DELETE SET NULL, -- NULL for anonymous responses
  submitted_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  is_completed BOOLEAN DEFAULT FALSE NOT NULL,
  completion_time INTEGER, -- Time in seconds to complete the survey
  ip_address INET, -- For anonymous survey tracking
  user_agent TEXT, -- Browser/device info for analytics
  response_metadata JSONB DEFAULT '{}'::jsonb, -- Additional metadata
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(survey_id, user_id) -- Prevent duplicate responses unless multiple responses allowed
);

-- Answers Table
CREATE TABLE answers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  response_id BIGINT NOT NULL REFERENCES user_responses(id) ON DELETE CASCADE,
  question_id BIGINT NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
  answer_text TEXT, -- For text-based answers
  answer_options JSONB DEFAULT '[]'::jsonb, -- For multiple choice/checkbox answers
  rating INTEGER CHECK (rating >= 1 AND rating <= 10), -- For rating questions (1-10 scale)
  numeric_value DECIMAL(15,2), -- For number questions
  date_value DATE, -- For date questions
  time_value TIME, -- For time questions
  email_value VARCHAR(255), -- For email questions
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Survey Analytics Table (for pre-computed analytics)
CREATE TABLE survey_analytics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  survey_id BIGINT NOT NULL REFERENCES surveys(id) ON DELETE CASCADE,
  question_id BIGINT REFERENCES questions(id) ON DELETE CASCADE,
  metric_type TEXT NOT NULL, -- 'response_rate', 'completion_rate', 'average_rating', etc.
  metric_value DECIMAL(15,4) NOT NULL,
  metric_data JSONB DEFAULT '{}'::jsonb, -- Additional metric data
  computed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Survey Invitations Table (for targeted survey invitations)
CREATE TABLE survey_invitations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  survey_id BIGINT NOT NULL REFERENCES surveys(id) ON DELETE CASCADE,
  user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
  email VARCHAR(255), -- For external invitations
  invitation_token VARCHAR(255) UNIQUE,
  status TEXT CHECK (status IN ('pending', 'accepted', 'declined', 'expired')) DEFAULT 'pending',
  sent_at TIMESTAMP WITH TIME ZONE,
  responded_at TIMESTAMP WITH TIME ZONE,
  expires_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes for Performance
CREATE INDEX idx_surveys_created_by ON surveys(created_by);
CREATE INDEX idx_surveys_status ON surveys(status);
CREATE INDEX idx_surveys_created_at ON surveys(created_at);
CREATE INDEX idx_surveys_start_end_dates ON surveys(start_date, end_date);

CREATE INDEX idx_questions_survey_id ON questions(survey_id);
CREATE INDEX idx_questions_type ON questions(type);
CREATE INDEX idx_questions_order ON questions("order");

CREATE INDEX idx_user_responses_survey_id ON user_responses(survey_id);
CREATE INDEX idx_user_responses_user_id ON user_responses(user_id);
CREATE INDEX idx_user_responses_submitted_at ON user_responses(submitted_at);
CREATE INDEX idx_user_responses_is_completed ON user_responses(is_completed);

CREATE INDEX idx_answers_response_id ON answers(response_id);
CREATE INDEX idx_answers_question_id ON answers(question_id);

CREATE INDEX idx_survey_analytics_survey_id ON survey_analytics(survey_id);
CREATE INDEX idx_survey_analytics_question_id ON survey_analytics(question_id);
CREATE INDEX idx_survey_analytics_metric_type ON survey_analytics(metric_type);

CREATE INDEX idx_survey_invitations_survey_id ON survey_invitations(survey_id);
CREATE INDEX idx_survey_invitations_user_id ON survey_invitations(user_id);
CREATE INDEX idx_survey_invitations_email ON survey_invitations(email);
CREATE INDEX idx_survey_invitations_token ON survey_invitations(invitation_token);

-- Triggers for updated_at
CREATE TRIGGER handle_surveys_updated_at
  BEFORE UPDATE ON surveys
  FOR EACH ROW
  EXECUTE PROCEDURE handle_updated_at();

CREATE TRIGGER handle_questions_updated_at
  BEFORE UPDATE ON questions
  FOR EACH ROW
  EXECUTE PROCEDURE handle_updated_at();

CREATE TRIGGER handle_user_responses_updated_at
  BEFORE UPDATE ON user_responses
  FOR EACH ROW
  EXECUTE PROCEDURE handle_updated_at();

CREATE TRIGGER handle_answers_updated_at
  BEFORE UPDATE ON answers
  FOR EACH ROW
  EXECUTE PROCEDURE handle_updated_at();

CREATE TRIGGER handle_survey_invitations_updated_at
  BEFORE UPDATE ON survey_invitations
  FOR EACH ROW
  EXECUTE PROCEDURE handle_updated_at();

-- Function to increment response count
CREATE OR REPLACE FUNCTION increment_response_count(survey_id_param BIGINT)
RETURNS VOID AS $$
BEGIN
    UPDATE surveys 
    SET response_count = response_count + 1 
    WHERE id = survey_id_param;
END;
$$ LANGUAGE plpgsql;

-- Function to get survey analytics
CREATE OR REPLACE FUNCTION get_survey_analytics(survey_id_param BIGINT)
RETURNS TABLE (
  total_responses BIGINT,
  completed_responses BIGINT,
  completion_rate DECIMAL(5,2),
  average_completion_time INTEGER,
  responses_by_date DATE,
  response_count INTEGER
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        COUNT(DISTINCT ur.id) as total_responses,
        COUNT(DISTINCT CASE WHEN ur.is_completed = true THEN ur.id END) as completed_responses,
        CASE 
            WHEN COUNT(DISTINCT ur.id) > 0 THEN 
                ROUND((COUNT(DISTINCT CASE WHEN ur.is_completed = true THEN ur.id END) * 100.0 / COUNT(DISTINCT ur.id)), 2)
            ELSE 0 
        END as completion_rate,
        ROUND(AVG(ur.completion_time))::INTEGER as average_completion_time,
        DATE(ur.submitted_at) as responses_by_date,
        COUNT(ur.id) as response_count
    FROM user_responses ur
    WHERE ur.survey_id = survey_id_param
    GROUP BY DATE(ur.submitted_at)
    ORDER BY responses_by_date DESC;
END;
$$ LANGUAGE plpgsql;

-- Function to get question analytics
CREATE OR REPLACE FUNCTION get_question_analytics(question_id_param BIGINT)
RETURNS TABLE (
  total_answers BIGINT,
  answer_text TEXT,
  answer_options JSONB,
  rating INTEGER,
  answer_count INTEGER,
  answer_percentage DECIMAL(5,2)
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        COUNT(a.id) as total_answers,
        a.answer_text,
        a.answer_options,
        a.rating,
        COUNT(a.id) as answer_count,
        CASE 
            WHEN (SELECT COUNT(*) FROM answers WHERE question_id = question_id_param) > 0 THEN 
                ROUND((COUNT(a.id) * 100.0 / (SELECT COUNT(*) FROM answers WHERE question_id = question_id_param)), 2)
            ELSE 0 
        END as answer_percentage
    FROM answers a
    WHERE a.question_id = question_id_param
    GROUP BY a.answer_text, a.answer_options, a.rating;
END;
$$ LANGUAGE plpgsql;

-- Since RLS is disabled in your current setup, we won't enable it for survey tables
-- This matches your current configuration where RLS is disabled

-- Confirmation
DO $$
BEGIN
    RAISE NOTICE '==========================================================================';
    RAISE NOTICE 'Comprehensive Survey Schema Created Successfully';
    RAISE NOTICE 'Tables created:';
    RAISE NOTICE '  - surveys (main survey table)';
    RAISE NOTICE '  - questions (survey questions)';
    RAISE NOTICE '  - user_responses (user responses)';
    RAISE NOTICE '  - answers (individual answers)';
    RAISE NOTICE '  - survey_analytics (pre-computed analytics)';
    RAISE NOTICE '  - survey_invitations (survey invitations)';
    RAISE NOTICE 'Features included:';
    RAISE NOTICE '  - Multiple question types (multiple choice, text, rating, etc.)';
    RAISE NOTICE '  - Anonymous and authenticated surveys';
    RAISE NOTICE '  - Survey scheduling (start/end dates)';
    RAISE NOTICE '  - Target audience filtering';
    RAISE NOTICE '  - Response analytics and reporting';
    RAISE NOTICE '  - Survey invitations';
    RAISE NOTICE '  - Advanced validation and settings';
    RAISE NOTICE 'RLS is disabled (matching your current setup)';
    RAISE NOTICE '==========================================================================';
END $$;
