-- Posts table schema for Voxa application
-- This creates the posts table and related tables for comments and likes

-- Posts table
create table posts (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  content text not null,
  title varchar(200),
  type text check (type in ('general', 'survey', 'announcement')) default 'general' not null,
  survey_id bigint references surveys(id) on delete set null,
  tags jsonb default '[]'::jsonb,
  is_pinned boolean default false not null,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Post comments table
create table post_comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references posts(id) on delete cascade,
  user_id bigint not null references users(id) on delete cascade,
  content text not null,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Post likes table
create table post_likes (
  id bigint generated by default as identity primary key,
  post_id bigint not null references posts(id) on delete cascade,
  user_id bigint not null references users(id) on delete cascade,
  created_at timestamp with time zone default now(),
  unique(post_id, user_id) -- Ensure a user can only like a post once
);

-- Indexes for better performance
create index idx_posts_user_id on posts(user_id);
create index idx_posts_type on posts(type);
create index idx_posts_created_at on posts(created_at);
create index idx_posts_is_pinned on posts(is_pinned);
create index idx_post_comments_post_id on post_comments(post_id);
create index idx_post_comments_user_id on post_comments(user_id);
create index idx_post_comments_created_at on post_comments(created_at);
create index idx_post_likes_post_id on post_likes(post_id);
create index idx_post_likes_user_id on post_likes(user_id);

-- Triggers for updated_at
create trigger handle_posts_updated_at
  before update on posts
  for each row
  execute procedure handle_updated_at();

create trigger handle_post_comments_updated_at
  before update on post_comments
  for each row
  execute procedure handle_updated_at();

-- Row Level Security (RLS) policies for posts
alter table posts enable row level security;
alter table post_comments enable row level security;
alter table post_likes enable row level security;

-- Posts table policies - Everyone can see all posts (public feed)
create policy "Everyone can view all posts" on posts
  for select using (true);

create policy "Authenticated users can create posts" on posts
  for insert with check (auth.uid()::text::bigint = user_id);

create policy "Post authors can update own posts" on posts
  for update using (auth.uid()::text::bigint = user_id);

create policy "Post authors can delete own posts" on posts
  for delete using (auth.uid()::text::bigint = user_id);

-- Post comments policies
create policy "Everyone can view all comments" on post_comments
  for select using (true);

create policy "Authenticated users can create comments" on post_comments
  for insert with check (auth.uid()::text::bigint = user_id);

create policy "Comment authors can update own comments" on post_comments
  for update using (auth.uid()::text::bigint = user_id);

create policy "Comment authors can delete own comments" on post_comments
  for delete using (auth.uid()::text::bigint = user_id);

-- Post likes policies
create policy "Everyone can view all likes" on post_likes
  for select using (true);

create policy "Authenticated users can create likes" on post_likes
  for insert with check (auth.uid()::text::bigint = user_id);

create policy "Users can delete own likes" on post_likes
  for delete using (auth.uid()::text::bigint = user_id);
