// This script creates the missing profile_activity_log table
// that's causing the profile update to fail

const { createClient } = require('@supabase/supabase-js');

require('dotenv').config();

const supabaseUrl = process.env.SUPABASE_URL;
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !supabaseServiceKey) {
  console.error('Missing Supabase configuration. Please check your .env file.');
  process.exit(1);
}

const supabaseAdmin = createClient(supabaseUrl, supabaseServiceKey);

async function createProfileActivityLog() {
  try {
    console.log('Creating profile_activity_log table...');
    
    // Create the table using raw SQL
    const { data, error } = await supabaseAdmin.rpc('exec_sql', {
      sql: `
        CREATE TABLE IF NOT EXISTS profile_activity_log (
          id BIGINT PRIMARY KEY DEFAULT (nextval('profile_activity_log_id_seq'::regclass)),
          user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          action VARCHAR(50) NOT NULL,
          old_values JSONB,
          new_values JSONB,
          created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
          ip_address INET,
          user_agent TEXT
        );
        
        -- Create index for better performance
        CREATE INDEX IF NOT EXISTS idx_profile_activity_log_user_id ON profile_activity_log(user_id);
        CREATE INDEX IF NOT EXISTS idx_profile_activity_log_created_at ON profile_activity_log(created_at);
        
        -- Create sequence if it doesn't exist
        CREATE SEQUENCE IF NOT EXISTS profile_activity_log_id_seq;
        ALTER SEQUENCE profile_activity_log_id_seq OWNED BY profile_activity_log.id;
      `
    });
    
    if (error) {
      console.error('Error creating table:', error);
      
      // Try alternative approach - create table step by step
      console.log('Trying alternative approach...');
      
      // First, try to create the table without the sequence
      const { data: altData, error: altError } = await supabaseAdmin
        .from('profile_activity_log')
        .select('*')
        .limit(1);
      
      if (altError && altError.message.includes('does not exist')) {
        console.log('Table does not exist, need to create it via Supabase dashboard or direct SQL');
        console.log('For now, let\'s create a simple version without triggers');
        
        // Create a minimal table structure
        const { error: createError } = await supabaseAdmin.rpc('exec_sql', {
          sql: `
            CREATE TABLE profile_activity_log (
              id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
              user_id BIGINT NOT NULL,
              action VARCHAR(50) NOT NULL,
              old_values JSONB,
              new_values JSONB,
              created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
            );
          `
        });
        
        if (createError) {
          console.error('Still cannot create table:', createError);
          console.log('You may need to create this table manually in the Supabase dashboard');
          return;
        }
      }
    }
    
    console.log('Table created successfully!');
    
    // Test the table
    const { data: testData, error: testError } = await supabaseAdmin
      .from('profile_activity_log')
      .select('count')
      .limit(1);
    
    if (testError) {
      console.error('Table test failed:', testError);
    } else {
      console.log('Table test passed!');
    }
    
  } catch (error) {
    console.error('Error:', error);
  }
}

createProfileActivityLog();
