-- Enhanced Voxa Supabase Database Schema
-- This SQL creates tables with proper role-based authentication and dashboard routing

-- Enable UUID extension for Supabase (PostgreSQL syntax)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Drop existing tables if they exist (for clean setup)
DROP TABLE IF EXISTS answers CASCADE;
DROP TABLE IF EXISTS responses CASCADE;
DROP TABLE IF EXISTS questions CASCADE;
DROP TABLE IF EXISTS surveys CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- Users table with enhanced role management
CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  role TEXT CHECK (role IN ('student', 'faculty', 'admin')) DEFAULT 'student' NOT NULL,
  student_id VARCHAR(20) UNIQUE,
  department VARCHAR(100),
  is_active BOOLEAN DEFAULT true NOT NULL,
  last_login TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Surveys table
CREATE TABLE surveys (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  description TEXT,
  created_by BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  status TEXT CHECK (status IN ('DRAFT', 'PUBLISHED', 'CLOSED')) DEFAULT 'PUBLISHED' NOT NULL,
  response_count INTEGER DEFAULT 0 NOT NULL,
  target_audience JSONB,
  start_date TIMESTAMP WITH TIME ZONE,
  end_date TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Questions table
CREATE TABLE questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  survey_id BIGINT NOT NULL REFERENCES surveys(id) ON DELETE CASCADE,
  text TEXT NOT NULL,
  type TEXT CHECK (type IN ('multiple', 'text', 'rating')) NOT NULL,
  "order" INTEGER NOT NULL,
  options JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Responses table
CREATE TABLE responses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  survey_id BIGINT NOT NULL REFERENCES surveys(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  submitted_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  is_completed BOOLEAN DEFAULT true NOT NULL,
  completion_time INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(survey_id, user_id)
);

-- Answers table
CREATE TABLE answers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  response_id BIGINT NOT NULL REFERENCES responses(id) ON DELETE CASCADE,
  question_id BIGINT NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
  answer_text TEXT,
  answer_options JSONB,
  rating INTEGER CHECK (rating >= 1 AND rating <= 5),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes for better performance
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_role ON users(role);
CREATE INDEX idx_users_student_id ON users(student_id);
CREATE INDEX idx_surveys_created_by ON surveys(created_by);
CREATE INDEX idx_surveys_status ON surveys(status);
CREATE INDEX idx_questions_survey_id ON questions(survey_id);
CREATE INDEX idx_responses_survey_id ON responses(survey_id);
CREATE INDEX idx_responses_user_id ON responses(user_id);
CREATE INDEX idx_answers_response_id ON answers(response_id);
CREATE INDEX idx_answers_question_id ON answers(question_id);

-- Function to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Triggers for updated_at
CREATE TRIGGER handle_users_updated_at
  BEFORE UPDATE ON users
  FOR EACH ROW
  EXECUTE PROCEDURE handle_updated_at();

CREATE TRIGGER handle_surveys_updated_at
  BEFORE UPDATE ON surveys
  FOR EACH ROW
  EXECUTE PROCEDURE handle_updated_at();

CREATE TRIGGER handle_questions_updated_at
  BEFORE UPDATE ON questions
  FOR EACH ROW
  EXECUTE PROCEDURE handle_updated_at();

CREATE TRIGGER handle_responses_updated_at
  BEFORE UPDATE ON responses
  FOR EACH ROW
  EXECUTE PROCEDURE handle_updated_at();

CREATE TRIGGER handle_answers_updated_at
  BEFORE UPDATE ON answers
  FOR EACH ROW
  EXECUTE PROCEDURE handle_updated_at();

-- Row Level Security (RLS) policies
-- Enable RLS on all tables
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE surveys ENABLE ROW LEVEL SECURITY;
ALTER TABLE questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE responses ENABLE ROW LEVEL SECURITY;
ALTER TABLE answers ENABLE ROW LEVEL SECURITY;

-- Users table policies
CREATE POLICY "Users can view own profile" ON users
  FOR SELECT USING (auth.uid()::text = id::text);

CREATE POLICY "Users can update own profile" ON users
  FOR UPDATE USING (auth.uid()::text = id::text);

CREATE POLICY "Admins can view all users" ON users
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM users 
      WHERE id = auth.uid()::text::bigint 
      AND role = 'admin'
      AND is_active = true
    )
  );

CREATE POLICY "Admins can insert users" ON users
  FOR INSERT WITH CHECK (
    EXISTS (
      SELECT 1 FROM users 
      WHERE id = auth.uid()::text::bigint 
      AND role = 'admin'
      AND is_active = true
    )
  );

CREATE POLICY "Admins can update all users" ON users
  FOR UPDATE USING (
    EXISTS (
      SELECT 1 FROM users 
      WHERE id = auth.uid()::text::bigint 
      AND role = 'admin'
      AND is_active = true
    )
  );

-- Faculty can view students in their department
CREATE POLICY "Faculty can view department students" ON users
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM users 
      WHERE id = auth.uid()::text::bigint 
      AND role = 'faculty'
      AND is_active = true
      AND department = users.department
    )
  );

-- Surveys table policies
CREATE POLICY "Everyone can view published surveys" ON surveys
  FOR SELECT USING (status = 'PUBLISHED');

CREATE POLICY "Survey creators can view own surveys" ON surveys
  FOR SELECT USING (created_by = auth.uid()::text::bigint);

CREATE POLICY "Faculty/Admin can create surveys" ON surveys
  FOR INSERT WITH CHECK (
    created_by = auth.uid()::text::bigint AND
    EXISTS (
      SELECT 1 FROM users 
      WHERE id = auth.uid()::text::bigint 
      AND role IN ('faculty', 'admin')
      AND is_active = true
    )
  );

CREATE POLICY "Survey creators can update own surveys" ON surveys
  FOR UPDATE USING (created_by = auth.uid()::text::bigint);

CREATE POLICY "Admins can manage all surveys" ON surveys
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM users 
      WHERE id = auth.uid()::text::bigint 
      AND role = 'admin'
      AND is_active = true
    )
  );

-- Questions table policies
CREATE POLICY "Everyone can view questions of published surveys" ON questions
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM surveys 
      WHERE surveys.id = questions.survey_id 
      AND surveys.status = 'PUBLISHED'
    )
  );

CREATE POLICY "Survey creators can manage questions" ON questions
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM surveys 
      WHERE surveys.id = questions.survey_id 
      AND surveys.created_by = auth.uid()::text::bigint
    )
  );

CREATE POLICY "Admins can manage all questions" ON questions
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM users 
      WHERE id = auth.uid()::text::bigint 
      AND role = 'admin'
      AND is_active = true
    )
  );

-- Responses table policies
CREATE POLICY "Users can view own responses" ON responses
  FOR SELECT USING (user_id = auth.uid()::text::bigint);

CREATE POLICY "Users can create own responses" ON responses
  FOR INSERT WITH CHECK (user_id = auth.uid()::text::bigint);

CREATE POLICY "Survey creators can view survey responses" ON responses
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM surveys 
      WHERE surveys.id = responses.survey_id 
      AND surveys.created_by = auth.uid()::text::bigint
    )
  );

CREATE POLICY "Admins can view all responses" ON responses
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM users 
      WHERE id = auth.uid()::text::bigint 
      AND role = 'admin'
      AND is_active = true
    )
  );

-- Answers table policies
CREATE POLICY "Users can view own answers" ON answers
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM responses 
      WHERE responses.id = answers.response_id 
      AND responses.user_id = auth.uid()::text::bigint
    )
  );

CREATE POLICY "Users can create own answers" ON answers
  FOR INSERT WITH CHECK (
    EXISTS (
      SELECT 1 FROM responses 
      WHERE responses.id = answers.response_id 
      AND responses.user_id = auth.uid()::text::bigint
    )
  );

CREATE POLICY "Survey creators can view survey answers" ON answers
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM responses 
      WHERE responses.id = answers.response_id
      AND EXISTS (
        SELECT 1 FROM surveys 
        WHERE surveys.id = responses.survey_id 
        AND surveys.created_by = auth.uid()::text::bigint
      )
    )
  );

CREATE POLICY "Admins can view all answers" ON answers
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM users 
      WHERE id = auth.uid()::text::bigint 
      AND role = 'admin'
      AND is_active = true
    )
  );

-- Functions for role-based access control
CREATE OR REPLACE FUNCTION get_user_role(user_id_param BIGINT)
RETURNS TEXT AS $$
BEGIN
  RETURN (
    SELECT role FROM users 
    WHERE id = user_id_param AND is_active = true
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to check if user can access dashboard
CREATE OR REPLACE FUNCTION can_access_dashboard(user_id_param BIGINT, dashboard_type TEXT)
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM users 
    WHERE id = user_id_param 
    AND is_active = true
    AND (
      (dashboard_type = 'student' AND role = 'student') OR
      (dashboard_type = 'faculty' AND role = 'faculty') OR
      (dashboard_type = 'admin' AND role = 'admin')
    )
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Insert default admin account
-- Email: admin, Password: password123 (will be hashed by application)
INSERT INTO users (first_name, last_name, email, password, role, student_id, department, is_active)
VALUES ('System', 'Administrator', 'admin', '$2a$10$rOzJqQjQjQjQjQjQjQjQjOzJqQjQjQjQjQjQjQjQjQjQjQjQjQjQjQjQjQj', 'admin', NULL, 'System Administration', true)
ON CONFLICT (email) DO NOTHING;

-- Create a view for dashboard access
CREATE VIEW user_dashboard_access AS
SELECT 
  u.id,
  u.first_name,
  u.last_name,
  u.email,
  u.role,
  u.last_login,
  CASE 
    WHEN u.role = 'student' THEN 'student_dashboard'
    WHEN u.role = 'faculty' THEN 'faculty_dashboard'
    WHEN u.role = 'admin' THEN 'admin_dashboard'
  END as dashboard_route,
  u.is_active
FROM users u
WHERE u.is_active = true;

-- Grant necessary permissions
GRANT SELECT ON user_dashboard_access TO authenticated;
GRANT EXECUTE ON FUNCTION get_user_role(BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION can_access_dashboard(BIGINT, TEXT) TO authenticated;
