-- Fix existing posts table to work with the application
-- This script handles the case where posts table already exists

-- First, check if posts table exists and get its structure
-- If it exists, we'll modify it to match what our application expects

-- Drop the existing posts table if it has wrong structure and recreate it
DROP TABLE IF EXISTS posts CASCADE;
DROP TABLE IF EXISTS post_comments CASCADE;
DROP TABLE IF EXISTS post_likes CASCADE;

-- Create posts table with correct structure
create table posts (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  content text not null,
  title varchar(200),
  type text check (type in ('general', 'survey', 'announcement')) default 'general' not null,
  survey_id bigint references surveys(id) on delete set null,
  tags jsonb default '[]'::jsonb,
  is_pinned boolean default false not null,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Post comments table
create table post_comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references posts(id) on delete cascade,
  user_id bigint not null references users(id) on delete cascade,
  content text not null,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Post likes table
create table post_likes (
  id bigint generated by default as identity primary key,
  post_id bigint not null references posts(id) on delete cascade,
  user_id bigint not null references users(id) on delete cascade,
  created_at timestamp with time zone default now(),
  unique(post_id, user_id) -- Ensure a user can only like a post once
);

-- Indexes for better performance
create index idx_posts_user_id on posts(user_id);
create index idx_posts_type on posts(type);
create index idx_posts_created_at on posts(created_at);
create index idx_posts_is_pinned on posts(is_pinned);
create index idx_post_comments_post_id on post_comments(post_id);
create index idx_post_comments_user_id on post_comments(user_id);
create index idx_post_comments_created_at on post_comments(created_at);
create index idx_post_likes_post_id on post_likes(post_id);
create index idx_post_likes_user_id on post_likes(user_id);

-- Triggers for updated_at
create trigger handle_posts_updated_at
  before update on posts
  for each row
  execute procedure handle_updated_at();

create trigger handle_post_comments_updated_at
  before update on post_comments
  for each row
  execute procedure handle_updated_at();

-- Since RLS is disabled in your current setup, we won't enable it for posts tables
-- This matches your current configuration where RLS is disabled

-- Confirmation
DO $$
BEGIN
    RAISE NOTICE '==========================================================================';
    RAISE NOTICE 'Posts tables have been recreated with correct structure';
    RAISE NOTICE 'Posts table: posts';
    RAISE NOTICE 'Comments table: post_comments';
    RAISE NOTICE 'Likes table: post_likes';
    RAISE NOTICE 'RLS is disabled (matching your current setup)';
    RAISE NOTICE '==========================================================================';
END $$;
