-- Voxa Supabase Database Schema
-- This SQL creates tables equivalent to the current MySQL/Sequelize models

-- Enable UUID extension for Supabase (PostgreSQL syntax)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Users table
create table users (
  id bigint generated by default as identity primary key,
  first_name varchar(50) not null,
  last_name varchar(50) not null,
  email varchar(100) unique not null,
  password varchar(255) not null,
  role text check (role in ('student', 'teacher', 'faculty', 'admin')) default 'student' not null,
  student_id varchar(20) unique,
  department varchar(100),
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Surveys table
create table surveys (
  id bigint generated by default as identity primary key,
  title varchar(200) not null,
  description text,
  created_by bigint not null references users(id) on delete cascade,
  status text check (status in ('DRAFT', 'PUBLISHED', 'CLOSED')) default 'PUBLISHED' not null,
  response_count integer default 0 not null,
  target_audience jsonb,
  start_date timestamp with time zone,
  end_date timestamp with time zone,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Questions table
create table questions (
  id bigint generated by default as identity primary key,
  survey_id bigint not null references surveys(id) on delete cascade,
  text text not null,
  type text check (type in ('multiple', 'text', 'rating')) not null,
  "order" integer not null,
  options jsonb,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Responses table
create table responses (
  id bigint generated by default as identity primary key,
  survey_id bigint not null references surveys(id) on delete cascade,
  user_id bigint not null references users(id) on delete cascade,
  submitted_at timestamp with time zone default now(),
  is_completed boolean default true not null,
  completion_time integer,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  unique(survey_id, user_id)
);

-- Answers table
create table answers (
  id bigint generated by default as identity primary key,
  response_id bigint not null references responses(id) on delete cascade,
  question_id bigint not null references questions(id) on delete cascade,
  answer_text text,
  answer_options jsonb,
  rating integer check (rating >= 1 and rating <= 5),
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Indexes for better performance
create index idx_users_email on users(email);
create index idx_users_role on users(role);
create index idx_surveys_created_by on surveys(created_by);
create index idx_surveys_status on surveys(status);
create index idx_questions_survey_id on questions(survey_id);
create index idx_responses_survey_id on responses(survey_id);
create index idx_responses_user_id on responses(user_id);
create index idx_answers_response_id on answers(response_id);
create index idx_answers_question_id on answers(question_id);

-- Function to automatically update updated_at timestamp
create or replace function handle_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- Triggers for updated_at
create trigger handle_users_updated_at
  before update on users
  for each row
  execute procedure handle_updated_at();

create trigger handle_surveys_updated_at
  before update on surveys
  for each row
  execute procedure handle_updated_at();

create trigger handle_questions_updated_at
  before update on questions
  for each row
  execute procedure handle_updated_at();

create trigger handle_responses_updated_at
  before update on responses
  for each row
  execute procedure handle_updated_at();

create trigger handle_answers_updated_at
  before update on answers
  for each row
  execute procedure handle_updated_at();

-- Row Level Security (RLS) policies
-- Enable RLS on all tables
alter table users enable row level security;
alter table surveys enable row level security;
alter table questions enable row level security;
alter table responses enable row level security;
alter table answers enable row level security;

-- Users table policies
create policy "Users can view own profile" on users
  for select using (auth.uid()::text = id::text);

create policy "Users can update own profile" on users
  for update using (auth.uid()::text = id::text);

create policy "Admins can view all users" on users
  for select using (
    exists (
      select 1 from users 
      where id = auth.uid()::text::bigint 
      and role = 'admin'
    )
  );

create policy "Admins can insert users" on users
  for insert with check (
    exists (
      select 1 from users 
      where id = auth.uid()::text::bigint 
      and role = 'admin'
    )
  );

-- Surveys table policies
create policy "Everyone can view published surveys" on surveys
  for select using (status = 'PUBLISHED');

create policy "Survey creators can view own surveys" on surveys
  for select using (created_by = auth.uid()::text::bigint);

create policy "Faculty/Admin can create surveys" on surveys
  for insert with check (
    created_by = auth.uid()::text::bigint and
    exists (
      select 1 from users 
      where id = auth.uid()::text::bigint 
      and role in ('faculty', 'admin')
    )
  );

create policy "Survey creators can update own surveys" on surveys
  for update using (created_by = auth.uid()::text::bigint);

-- Questions table policies
create policy "Everyone can view questions of published surveys" on questions
  for select using (
    exists (
      select 1 from surveys 
      where surveys.id = questions.survey_id 
      and surveys.status = 'PUBLISHED'
    )
  );

create policy "Survey creators can manage questions" on questions
  for all using (
    exists (
      select 1 from surveys 
      where surveys.id = questions.survey_id 
      and surveys.created_by = auth.uid()::text::bigint
    )
  );

-- Responses table policies
create policy "Users can view own responses" on responses
  for select using (user_id = auth.uid()::text::bigint);

create policy "Users can create own responses" on responses
  for insert with check (user_id = auth.uid()::text::bigint);

create policy "Survey creators can view survey responses" on responses
  for select using (
    exists (
      select 1 from surveys 
      where surveys.id = responses.survey_id 
      and surveys.created_by = auth.uid()::text::bigint
    )
  );

-- Answers table policies
create policy "Users can view own answers" on answers
  for select using (
    exists (
      select 1 from responses 
      where responses.id = answers.response_id 
      and responses.user_id = auth.uid()::text::bigint
    )
  );

create policy "Users can create own answers" on answers
  for insert with check (
    exists (
      select 1 from responses 
      where responses.id = answers.response_id 
      and responses.user_id = auth.uid()::text::bigint
    )
  );

create policy "Survey creators can view survey answers" on answers
  for select using (
    exists (
      select 1 from responses 
      where responses.id = answers.response_id
      and exists (
        select 1 from surveys 
        where surveys.id = responses.survey_id 
        and surveys.created_by = auth.uid()::text::bigint
      )
    )
  );
